;;; modal-variant.el --- `modal' variants per major mode.  -*- lexical-binding: t; -*-

;; Copyright (C) 2026  Nicolás Pablo González Carrasco

;; Author: Nicolás Pablo González Carrasco <nicolaspablo.gc@gmail.com>
;; Keywords: convenience, tools

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; This package lets you define `modal-mode' variants per major mode.

;; A variant is a specialized version of `modal-mode' that is only active when
;; the major mode is active.  It has its own map allowing for redefining
;; bindings per major mode.

;; The typical usage involves creating a variant for a mode, for example,
;; python-mode:

;;     (modal-variant-define python-mode)

;; Then you can start definining bindings for it:

;;     (define-key modal-python-mode-map ...)

;; Finally, instead of calling `modal-mode' you call `modal-variant-mode'
;; as the intended replacement for it: if a variant exists (e.g.,
;; \+`modal-python-mode') it activates it; if not, it activates bare
;; `modal-mode'.

;; For more details see the docstring of `modal-variant-define'.

;; For a multi mode convenience construct, use `modal-variants-define':

;;     (modal-variants-define mode-1 mode-2 ... mode-n)

;;; Code:

(require 'modal)

(defun modal-variant--register (variant-mode variant-map)
  "Add an entry to `modal--mode-map-alist' for VARIANT-MODE.

VARIANT-MODE is the variant mode's symbol.
VARIANT-MAP is the variant mode's keymap.

Preserves first position of `modal--mode-map-alist' which is reserved for
`modal-global-mode'."
  (unless (assq variant-mode modal--mode-map-alist)
    (setcdr modal--mode-map-alist
            (cons (cons variant-mode variant-map)
                  (cdr modal--mode-map-alist)))))

(defun modal-variant--name-of (mode)
  "Return the modal variant name (a symbol) of MODE (also a symbol)."
  (intern (format "modal-%s" (symbol-name mode))))

(defcustom modal-variant-lighter " [~]"
  "Lighter used in modal variants."
  :group 'modal
  :type 'string)

(defmacro modal-variant-define (mode)
  "Define a specialized `modal-mode' variant for MODE.

MODE is the unquoted symbol of the major mode.

Defining a variant creates a new minor mode, \\=`modal-MODE'.  For
example, the following expression

    (modal-variant-define emacs-lisp-mode)

creates \\=`modal-emacs-lisp-mode' variant minor mode."
  (let* ((variant-mode (modal-variant--name-of mode))
         (variant-map  (intern (format "%s-map" (symbol-name variant-mode)))))
    `(progn
       (defvar ,variant-map
         (let ((map (make-sparse-keymap)))
           (set-keymap-parent map modal-mode-map)
           map)
         ,(format "Keymap for `%s'.\nGenerated by `modal-variant-define'."
                  variant-mode))
       (define-minor-mode ,variant-mode
         ,(format "`modal-mode' variant for `%s'.\nGenerated by `modal-variant-define'."
                  mode)
         :lighter modal-variant-lighter
         :keymap ,variant-map
         ;; Also run "parent" `modal-mode' hooks.
         (run-hooks 'modal-mode-hook))
       (modal-variant--register ',variant-mode ,variant-map)
       ',variant-mode)))

(defmacro modal-variants-define (&rest modes)
  "Like `modal-variant-define' but for all MODES."
  `(progn
     ,@(mapcar (lambda (mode) `(modal-variant-define ,mode))
               modes)))

(defun modal-variant-mode (&optional arg)
  "Activate the `variant-mode' for the current mode.
It checks for the current mode up to its parent modes.
If no variant exists, fallback to `modal-mode'."
  (interactive "P")
  (let ((mode (car (seq-filter (lambda (mode) (fboundp (modal-variant--name-of mode)))
			       (derived-mode-all-parents major-mode)))))
    (funcall (if mode (modal-variant--name-of mode) 'modal-mode)
	     (if (not arg)
		 'toggle
	       arg))))

(provide 'modal-variant)
;;; modal-variant.el ends here
